#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket"
        start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping aesdsocket"
        start-stop-daemon -K -n aesdsocket
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0


# additional comments
# start-stop-daemon is a utility in Linux that is primarily used for managing system services and applications. 
#It is commonly found in Debian-based systems (like Ubuntu) and is part of the init system that controls how services are started and stopped.
