#!/bin/sh

case "$1" in
	start)
		echo "beginning aesdsocket from asedsocket-start-stop"
		start-stop-daemon --start --background --exec /usr/bin/aesdsocket -- -d
		;;
	stop)
		echo "stopping aesdsocket from asedsocket-start-stop"
		start-stop-daemon --stop --exec /usr/bin/aesdsocket
		;;
	*)
		echo "Usage: $0 {start|stop}"
		echo "asedsocket-start-stop errorirng"
		exit 1
		;;
esac

exit 0


# additional comments
# start-stop-daemon is a utility in Linux that is primarily used for managing system services and applications. 
#It is commonly found in Debian-based systems (like Ubuntu) and is part of the init system that controls how services are started and stopped.
